#theme: jekyll-theme-hydeout
remote_theme: fongandrew/hydeout
paginate: 2

title: the next screen
description: Better software and outcomes, one screen at a time

disqus:
    shortname: thenextscreen

plugins: [jekyll-paginate]